In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [49]:
a = np.arange(1,21)
b = np.arange(1,21)
c = np.ones(20,)*2

res = pow(c, a)/b

res

array([  2.00000000e+00,   2.00000000e+00,   2.66666667e+00,
         4.00000000e+00,   6.40000000e+00,   1.06666667e+01,
         1.82857143e+01,   3.20000000e+01,   5.68888889e+01,
         1.02400000e+02,   1.86181818e+02,   3.41333333e+02,
         6.30153846e+02,   1.17028571e+03,   2.18453333e+03,
         4.09600000e+03,   7.71011765e+03,   1.45635556e+04,
         2.75941053e+04,   5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [50]:
a = np.zeros((1,6))
a = a + 0.1
b = np.zeros((1,6))
b = b + 0.2

i_a = np.arange(0,6)*3
i_b = np.arange(0,6)*4

a = pow(a,i_a)
b = pow(b,i_b)
c = a*b
res = np.sum(c)

print('c =', c)
print(res)

c = [[  1.00000000e+00   1.60000000e-06   2.56000000e-12   4.09600000e-18
    6.55360000e-24   1.04857600e-29]]
1.0000016


**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [51]:
A = np.zeros((8,8), dtype=int)
A[::2,::2] = 1
A[1::2,1::2] = 1

A

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [52]:
X = np.random.random((5, 2))

x = X[::, 0:1:]
y = X[::, 1:2:]

r = pow((x+y),0.5)
phi = np.arctan(y/x)
R = np.column_stack((r, phi))
R

array([[ 0.84050738,  0.41159368],
       [ 0.66205957,  1.39906712],
       [ 1.19340534,  0.50163685],
       [ 0.85992279,  1.55861464],
       [ 0.82215808,  0.02163617]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [57]:
X = np.random.random((10, 10))

max = np.argmax(X)
max

85

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [60]:
X = np.random.random((10, 2))
Y = np.random.random((1, 2))

x = (X[:,0] - Y[0,0])
y = (X[:,1] - Y[0,1])         
res = X[np.argmin(np.sqrt(x ** 2 + y ** 2)), :]

res

array([ 0.81181469,  0.55050982])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [41]:
x = np.arange(-3, 3.001, 0.1)

@np.vectorize
def f(x):
    if x < 0:
        return x**2 + 2*x + 6
    elif x < 2:
        return x + 6
    else: 
        return x**2 + 4*x - 4

res = f(x)
res

array([  9.  ,   8.61,   8.24,   7.89,   7.56,   7.25,   6.96,   6.69,
         6.44,   6.21,   6.  ,   5.81,   5.64,   5.49,   5.36,   5.25,
         5.16,   5.09,   5.04,   5.01,   5.  ,   5.01,   5.04,   5.09,
         5.16,   5.25,   5.36,   5.49,   5.64,   5.81,   6.  ,   6.1 ,
         6.2 ,   6.3 ,   6.4 ,   6.5 ,   6.6 ,   6.7 ,   6.8 ,   6.9 ,
         7.  ,   7.1 ,   7.2 ,   7.3 ,   7.4 ,   7.5 ,   7.6 ,   7.7 ,
         7.8 ,   7.9 ,   8.  ,   8.81,   9.64,  10.49,  11.36,  12.25,
        13.16,  14.09,  15.04,  16.01,  17.  ])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [61]:
X = np.random.random((10, 10))

mean = np.mean(X, axis = 1)
X = X - mean
print('mean = ', mean)
X

mean =  [ 0.55171344  0.56972875  0.51388445  0.46144404  0.51703613  0.48539511
  0.46256803  0.48945828  0.43997892  0.32872236]


array([[ 0.29836227, -0.55778822,  0.00246262,  0.33435027, -0.4312854 ,
        -0.40951108,  0.35590445,  0.17270359,  0.40527867,  0.52672773],
       [-0.38714732,  0.06730667,  0.42970487,  0.27946482, -0.35202913,
         0.3436924 ,  0.12437332,  0.07885974,  0.10220993,  0.19092269],
       [-0.01899643, -0.00761787, -0.00635205, -0.17319017,  0.09565942,
         0.45445581, -0.23573145, -0.21575671,  0.03649616,  0.38994825],
       [ 0.28116493,  0.29597837, -0.4361275 ,  0.01527677, -0.21730553,
        -0.07086916, -0.04566939,  0.20062006, -0.26198375,  0.03342607],
       [-0.44281816, -0.28888477,  0.40597496,  0.29883556, -0.42313755,
         0.4696594 ,  0.10127334, -0.05482581,  0.43621883, -0.15186401],
       [ 0.02904447, -0.1071998 , -0.32036143, -0.20385087, -0.02369486,
         0.47737489,  0.13899251, -0.10272322, -0.04907214,  0.19551204],
       [-0.30289703, -0.45892774, -0.14168608,  0.53214739,  0.2012159 ,
        -0.13244018, -0.23526214, -0.09379326

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [30]:
X = np.random.normal(loc=5, scale=2., size=1000)

M = np.mean(X)
sigma = np.std(X)
D = sigma**2

print('M = ', M, '; ', 'D = ', D)

M =  4.92453900146 ;  D =  3.86598529224


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [48]:
X = np.zeros((5,5))

X[0:5, :] = np.arange(0,5)
X[1, :] = np.roll(X[0, :], -1)
X[2, :] = np.roll(X[1, :], -1)
X[3, :] = np.roll(X[2, :], -1)
X[4, :] = np.roll(X[3, :], -1)

X

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.,  0.],
       [ 2.,  3.,  4.,  0.,  1.],
       [ 3.,  4.,  0.,  1.,  2.],
       [ 4.,  0.,  1.,  2.,  3.]])